name: Build disco

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        CGO_ENABLED: 0
        GO111MODULE: on
      run: |
        diff -au <(gofmt -s -d .) <(printf "")
        go test -v ./...
        docker build . -t "disco:latest"

